#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/env.sh"
# Do not mount the host home directory. /root and the writable image are in /tmp.
ENV_ARGS=()
for key in MINESWEEPER_RUN_ROOT XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_STATE_HOME \
    HF_HOME HF_HUB_CACHE HF_XET_CACHE HF_DATASETS_CACHE PIP_CACHE_DIR UV_CACHE_DIR \
    TORCH_HOME TORCH_EXTENSIONS_DIR TORCHINDUCTOR_CACHE_DIR TRITON_CACHE_DIR CUDA_CACHE_PATH \
    FLASHINFER_WORKSPACE_BASE WANDB_DIR WANDB_CACHE_DIR WANDB_CONFIG_DIR WANDB_DATA_DIR \
    TMPDIR RAY_TMPDIR PARALLEL_HOME PYTHONDONTWRITEBYTECODE PYTHONNOUSERSITE PYTHONUNBUFFERED \
    TOKENIZERS_PARALLELISM HF_HUB_DISABLE_TELEMETRY RAY_USAGE_STATS_ENABLED \
    WORK HF_MODEL MINESWEEPER_DIR NVIDIA_VISIBLE_DEVICES NVIDIA_DRIVER_CAPABILITIES \
    CUDA_VISIBLE_DEVICES CUDA_DEVICE_MAX_CONNECTIONS NCCL_NVLS_ENABLE \
    FLASHINFER_DISABLE_VERSION_CHECK MILES_EXPERIMENTAL_ROLLOUT_REFACTOR OMP_NUM_THREADS \
    ADVANTAGE_ESTIMATOR GRACEFULRL_EPS GRACEFUL_REWARD MINESWEEPER_SMOKE_TEST \
    WANDB_API_KEY WANDB_MODE HF_TOKEN; do
    if [[ -n "${!key:-}" ]]; then ENV_ARGS+=(--env "$key"); fi
done
MOUNT_ARGS=(--mount "$MINESWEEPER_RUN_ROOT:$MINESWEEPER_RUN_ROOT")
if [[ -f "${HOME}/.netrc" ]]; then
    MOUNT_ARGS+=(--mount "${HOME}/.netrc:/root/.netrc:ro,bind,x-create=file")
fi
exec enroot start --root --rw \
    "${MOUNT_ARGS[@]}" \
    "${ENV_ARGS[@]}" miles-minesweeper "$@"
